###
POST http://localhost:8080/products/authenticate
Content-Type: application/json

{
  "username": "Vikram",
  "password": "password"
}

###Response

HTTP/1.1 200
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: text/plain;charset=UTF-8
Content-Length: 132
Date: Wed, 22 May 2024 08:00:45 GMT

eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJWaWtyYW0iLCJpYXQiOjE3MTYzNjQ4NDUsImV4cCI6MTcxNjM2NjY0NX0.dAjDdCbnLVSb5WB_iQdSfFQTURIyuvOEKcaxXDUhB7A

Response code: 200; Time: 721ms (721 ms); Content length: 132 bytes (132 B)

<> 2024-05-22T133045.200.txt

###
GET http://localhost:8080/products/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJWaWtyYW0iLCJpYXQiOjE3MTYzNjQ4NDUsImV4cCI6MTcxNjM2NjY0NX0.dAjDdCbnLVSb5WB_iQdSfFQTURIyuvOEKcaxXDUhB7A

<> 2024-05-22T133234.200.json